import type { ServiceProvider, Event, Ticket, CatalogueItem, Document, Invitation, SpecialBanner, InboxMessage } from './types';

export const MOCK_PROVIDERS: ServiceProvider[] = [
  {
    id: 1,
    name: 'Roki Samuna',
    phone: '0722123456',
    whatsapp: '254722123456',
    service: 'Electronics Expert',
    avatarUrl: 'https://picsum.photos/seed/rokis/100/100',
    coverImageUrl: 'https://picsum.photos/seed/rokicover/600/400',
    rating: 4.9,
    distanceKm: 1.7,
    hourlyRate: 650,
    rateType: 'per hour',
    currency: 'Ksh',
    isVerified: true,
    about: 'I am a highly skilled electronics expert with over 10 years of experience fixing everything from phones to home appliances.',
    works: ['https://picsum.photos/seed/work1/400/400', 'https://picsum.photos/seed/work2/400/400', 'https://picsum.photos/seed/work3/400/400'],
    category: 'Home',
    location: 'Westlands, Nairobi',
    isOnline: true,
    accountType: 'individual',
    flagCount: 0,
    views: 124,
    cta: ['call', 'whatsapp'],
  },
  {
    id: 2,
    name: 'Jamila Ahusn',
    phone: '0722234567',
    whatsapp: '254722234567',
    service: 'Professional Painter',
    avatarUrl: 'https://picsum.photos/seed/jamila/100/100',
    coverImageUrl: 'https://picsum.photos/seed/jamilacover/600/400',
    rating: 4.9,
    distanceKm: 1.7,
    hourlyRate: 250,
    rateType: 'per sqm',
    currency: 'Ksh',
    isVerified: true,
    about: 'Transforming spaces with color and precision. With over 7 years of industry experience, I bring life to walls and homes.',
    works: ['https://picsum.photos/seed/paint1/400/400', 'https://picsum.photos/seed/paint2/400/400', 'https://picsum.photos/seed/paint3/400/400'],
    category: 'Home',
    location: 'Kileleshwa, Nairobi',
    isOnline: false,
    accountType: 'individual',
    flagCount: 1,
    views: 230,
    cta: ['call', 'whatsapp'],
  },
    {
    id: 3,
    name: 'David Otieno',
    phone: '0722345678',
    whatsapp: '254722345678',
    service: 'Boda Boda Rider',
    avatarUrl: 'https://picsum.photos/seed/david/100/100',
    coverImageUrl: 'https://picsum.photos/seed/davidcover/600/400',
    rating: 4.7,
    distanceKm: 0.5,
    hourlyRate: 100,
    rateType: 'per task',
    currency: 'Ksh',
    isVerified: false,
    about: 'Quick and safe transport around the city. I know all the shortcuts to get you there on time.',
    works: [],
    category: 'Transport',
    location: 'CBD, Nairobi',
    isOnline: true,
    accountType: 'individual',
    flagCount: 0,
    views: 88,
    cta: ['call'],
  },
  {
    id: 4,
    name: 'St. John Ambulance',
    phone: '0722456789',
    whatsapp: '254722456789',
    service: 'Emergency Medical Services',
    avatarUrl: 'https://picsum.photos/seed/junaed/100/100',
    coverImageUrl: 'https://picsum.photos/seed/junaedcover/600/400',
    rating: 4.9,
    distanceKm: 3.5,
    hourlyRate: 5000,
    rateType: 'per task',
    currency: 'Ksh',
    isVerified: true,
    about: '24/7 emergency medical response and ambulance services. Our certified paramedics are ready to assist you in any medical emergency.',
    works: ['https://picsum.photos/seed/web1/400/400', 'https://picsum.photos/seed/web2/400/400', 'https://picsum.photos/seed/web3/400/400'],
    category: 'Emergency',
    location: 'Upper Hill, Nairobi',
    isOnline: true,
    accountType: 'organization',
    flagCount: 0,
    views: 312,
    cta: ['call'],
  },
  {
    id: 5,
    name: 'Amina Yusuf',
    phone: '0722567890',
    whatsapp: '254722567890',
    service: 'Gas Delivery',
    avatarUrl: 'https://picsum.photos/seed/amina/100/100',
    coverImageUrl: 'https://picsum.photos/seed/aminacover/600/400',
    rating: 4.8,
    distanceKm: 0.8,
    hourlyRate: 100,
    rateType: 'per task',
    currency: 'Ksh',
    isVerified: true,
    about: 'Quick and safe cooking gas delivery right to your doorstep. Never run out of gas again.',
    works: [],
    category: 'Gas',
    location: 'Parklands, Nairobi',
    isOnline: true,
    accountType: 'individual',
    flagCount: 0,
    views: 95,
    cta: ['call', 'whatsapp'],
  },
  {
    id: 6,
    name: 'Ben Carter Events',
    phone: '0722678901',
    whatsapp: '254722678901',
    service: 'Event Planning & Catering',
    avatarUrl: 'https://picsum.photos/seed/ben/100/100',
    coverImageUrl: 'https://picsum.photos/seed/bencover/600/400',
    rating: 4.9,
    distanceKm: 1.2,
    hourlyRate: 1000,
    rateType: 'per hour',
    currency: 'Ksh',
    isVerified: true,
    about: 'Full-service event planning and catering for weddings, corporate events, and parties. Let us make your event unforgettable.',
    works: [],
    category: 'Event',
    location: 'Karen, Nairobi',
    isOnline: false,
    accountType: 'organization',
    flagCount: 0,
    views: 180,
    cta: ['book', 'catalogue'],
  },
  {
    id: 7,
    name: 'Maria Wanjiru',
    phone: '0722789012',
    whatsapp: '254722789012',
    service: 'Mama Fua (Laundry)',
    avatarUrl: 'https://picsum.photos/seed/maria/100/100',
    coverImageUrl: 'https://picsum.photos/seed/mariacover/600/400',
    rating: 5.0,
    distanceKm: 2.5,
    hourlyRate: 200,
    rateType: 'per day',
    currency: 'Ksh',
    isVerified: true,
    about: 'Professional laundry and cleaning services. Your clothes will thank you!',
    works: [],
    category: 'Home',
    location: 'Lavington, Nairobi',
    isOnline: true,
    accountType: 'individual',
    flagCount: 0,
    views: 215,
    cta: ['call', 'whatsapp'],
  },
  {
    id: 8,
    name: 'Samuel Electric',
    phone: '0722890123',
    whatsapp: '254722890123',
    service: 'Electrician',
    avatarUrl: 'https://picsum.photos/seed/samuel/100/100',
    coverImageUrl: 'https://picsum.photos/seed/samuelcover/600/400',
    rating: 4.6,
    distanceKm: 4.1,
    hourlyRate: 500,
    rateType: 'per hour',
    currency: 'Ksh',
    isVerified: true,
    about: 'Certified electrician for all your wiring, installation, and repair needs. Safety and quality guaranteed.',
    works: [],
    category: 'Home',
    location: 'South C, Nairobi',
    isOnline: true,
    accountType: 'individual',
    flagCount: 0,
    views: 150,
    cta: ['call'],
  },
  {
    id: 9,
    name: 'Nairobi Fire Dept.',
    phone: '999',
    service: 'Fire & Rescue',
    avatarUrl: 'https://picsum.photos/seed/firedpt/100/100',
    coverImageUrl: 'https://picsum.photos/seed/firecover/600/400',
    rating: 5.0,
    distanceKm: 2.1,
    hourlyRate: 0,
    rateType: 'per task',
    currency: 'Ksh',
    isVerified: true,
    about: 'Official fire and rescue services for Nairobi County. Call 999 for immediate assistance.',
    works: [],
    category: 'Emergency',
    location: 'Tom Mboya St, Nairobi',
    isOnline: true,
    accountType: 'organization',
    flagCount: 0,
    views: 450,
    cta: ['call'],
  },
  {
    id: 10,
    name: 'Festive Planners',
    phone: '0712987654',
    service: 'Wedding Planner',
    avatarUrl: 'https://picsum.photos/seed/festive/100/100',
    coverImageUrl: 'https://picsum.photos/seed/festivecover/600/400',
    rating: 4.9,
    distanceKm: 5.5,
    hourlyRate: 1200,
    rateType: 'per hour',
    currency: 'Ksh',
    isVerified: true,
    about: 'Creating beautiful and memorable weddings is our passion. We handle every detail, so you can enjoy your special day.',
    works: [],
    category: 'Event',
    location: 'Runda, Nairobi',
    isOnline: false,
    accountType: 'organization',
    flagCount: 0,
    views: 198,
    cta: ['book'],
  },
  {
    id: 11,
    name: 'Grace Mwangi',
    phone: '0712345678',
    whatsapp: '254712345678',
    service: 'Taxi Driver',
    avatarUrl: 'https://picsum.photos/seed/grace/100/100',
    coverImageUrl: 'https://picsum.photos/seed/gracecover/600/400',
    rating: 4.8,
    distanceKm: 1.1,
    hourlyRate: 300,
    rateType: 'per km',
    currency: 'Ksh',
    isVerified: true,
    about: 'Reliable and professional taxi services. Clean car, safe driver.',
    works: [],
    category: 'Transport',
    location: 'Kilimani, Nairobi',
    isOnline: true,
    accountType: 'individual',
    flagCount: 0,
    views: 132,
    cta: ['call', 'whatsapp'],
  },
  {
    id: 12,
    name: 'Peter Kamau',
    phone: '0733112233',
    service: 'Plumber',
    avatarUrl: 'https://picsum.photos/seed/peter/100/100',
    coverImageUrl: 'https://picsum.photos/seed/petercover/600/400',
    rating: 4.5,
    distanceKm: 3.2,
    hourlyRate: 450,
    rateType: 'per hour',
    currency: 'Ksh',
    isVerified: false,
    about: '24/7 plumbing services. Leaky pipes, clogged drains, new installations - I do it all.',
    works: [],
    category: 'Home',
    location: 'Embakasi, Nairobi',
    isOnline: true,
    accountType: 'individual',
    flagCount: 2,
    views: 76,
    cta: ['call'],
  },
  {
    id: 13,
    name: 'Sarah Chen',
    phone: '0744556677',
    whatsapp: '254744556677',
    service: 'Makeup Artist',
    avatarUrl: 'https://picsum.photos/seed/sarah/100/100',
    coverImageUrl: 'https://picsum.photos/seed/sarahcover/600/400',
    catalogueBannerUrl: 'https://picsum.photos/seed/sarahcatbanner/800/400',
    rating: 4.9,
    distanceKm: 6.1,
    hourlyRate: 2000,
    rateType: 'per appearance',
    currency: 'Ksh',
    isVerified: true,
    about: 'Professional makeup artist for weddings, photoshoots, and special events. Let me enhance your natural beauty.',
    works: ['https://picsum.photos/seed/makeup1/400/400', 'https://picsum.photos/seed/makeup2/400/400'],
    category: 'Personal',
    location: 'Gigiri, Nairobi',
    isOnline: false,
    accountType: 'individual',
    flagCount: 0,
    views: 289,
    cta: ['book', 'catalogue'],
  },
  {
    id: 14,
    name: 'Quick-Go Delivery',
    phone: '0755889900',
    service: 'Courier Services',
    avatarUrl: 'https://picsum.photos/seed/qgo/100/100',
    coverImageUrl: 'https://picsum.photos/seed/qgocover/600/400',
    rating: 4.7,
    distanceKm: 0.2,
    hourlyRate: 150,
    rateType: 'per task',
    currency: 'Ksh',
    isVerified: true,
    about: 'Fast and reliable document and parcel delivery within Nairobi and its environs.',
    works: [],
    category: 'Delivery',
    location: 'CBD, Nairobi',
    isOnline: true,
    accountType: 'organization',
    flagCount: 0,
    views: 110,
    cta: ['call'],
  },
  {
    id: 15,
    name: 'Safari Trails',
    phone: '0766112233',
    service: 'Tour Guide',
    avatarUrl: 'https://picsum.photos/seed/safari/100/100',
    coverImageUrl: 'https://picsum.photos/seed/safaricover/600/400',
    rating: 5.0,
    distanceKm: 8.0,
    hourlyRate: 2500,
    rateType: 'per day',
    currency: 'Ksh',
    isVerified: true,
    about: 'Discover the beauty of Kenya with an experienced and knowledgeable tour guide. Custom safari packages available.',
    works: ['https://picsum.photos/seed/safari1/400/400', 'https://picsum.photos/seed/safari2/400/400'],
    category: 'Travel',
    location: 'Karen, Nairobi',
    isOnline: false,
    accountType: 'organization',
    flagCount: 0,
    views: 350,
    cta: ['book'],
  },
  {
    id: 16,
    name: 'TotalEnergies Gas',
    phone: '0777334455',
    service: 'Gas Refill Station',
    avatarUrl: 'https://picsum.photos/seed/total/100/100',
    coverImageUrl: 'https://picsum.photos/seed/totalcover/600/400',
    rating: 4.6,
    distanceKm: 2.8,
    hourlyRate: 120,
    rateType: 'per task',
    currency: 'Ksh',
    isVerified: true,
    about: 'Official TotalEnergies gas distributor. We offer refills and new cylinders with free safety checks.',
    works: [],
    category: 'Gas',
    location: 'Ngong Road, Nairobi',
    isOnline: true,
    accountType: 'organization',
    flagCount: 0,
    views: 80,
    cta: ['call'],
  },
  {
    id: 17,
    name: 'Fitness Pro Gym',
    phone: '0788990011',
    service: 'Personal Trainer',
    avatarUrl: 'https://picsum.photos/seed/gym/100/100',
    coverImageUrl: 'https://picsum.photos/seed/gymcover/600/400',
    rating: 4.8,
    distanceKm: 1.5,
    hourlyRate: 800,
    rateType: 'per hour',
    currency: 'Ksh',
    isVerified: false,
    about: 'Certified personal trainers to help you achieve your fitness goals. Personalized workout and nutrition plans.',
    works: [],
    category: 'Personal',
    location: 'Westlands, Nairobi',
    isOnline: true,
    accountType: 'organization',
    flagCount: 0,
    views: 145,
    cta: ['book'],
  },
  {
    id: 18,
    name: 'FoodDash',
    phone: '0799112233',
    service: 'Food Delivery',
    avatarUrl: 'https://picsum.photos/seed/food/100/100',
    coverImageUrl: 'https://picsum.photos/seed/foodcover/600/400',
    rating: 4.5,
    distanceKm: 0.9,
    hourlyRate: 100,
    rateType: 'per task',
    currency: 'Ksh',
    isVerified: true,
    about: 'Craving your favorite meal? We deliver from the best restaurants in town, right to your doorstep.',
    works: [],
    category: 'Delivery',
    location: 'Kilimani, Nairobi',
    isOnline: true,
    accountType: 'organization',
    flagCount: 0,
    views: 160,
    cta: ['call'],
  },
  {
    id: 19,
    name: 'City Movers',
    phone: '0711223344',
    service: 'Moving Company',
    avatarUrl: 'https://picsum.photos/seed/movers/100/100',
    coverImageUrl: 'https://picsum.photos/seed/moverscover/600/400',
    rating: 4.9,
    distanceKm: 4.5,
    hourlyRate: 1500,
    rateType: 'per cbm',
    currency: 'Ksh',
    isVerified: true,
    about: 'Professional and affordable moving services for homes and offices. We make moving easy and stress-free.',
    works: [],
    category: 'Transport',
    location: 'Industrial Area, Nairobi',
    isOnline: false,
    accountType: 'organization',
    flagCount: 0,
    views: 175,
    cta: ['call'],
  },
  {
    id: 20,
    name: 'BrightSparks Tutors',
    phone: '0723456789',
    service: 'Academic Tutor',
    avatarUrl: 'https://picsum.photos/seed/tutor/100/100',
    coverImageUrl: 'https://picsum.photos/seed/tutorcover/600/400',
    rating: 4.9,
    distanceKm: 3.3,
    hourlyRate: 700,
    rateType: 'per hour',
    currency: 'Ksh',
    isVerified: true,
    about: 'Experienced tutors for all subjects and levels. We help students excel academically and build confidence.',
    works: [],
    category: 'Personal',
    location: 'Lavington, Nairobi',
    isOnline: true,
    accountType: 'organization',
    flagCount: 0,
    views: 205,
    cta: ['book'],
  }
];

export const MOCK_EVENTS: Event[] = [
    {
        id: 1,
        name: 'Sauti Sol Live in Concert',
        date: '2024-12-15T19:00:00',
        location: 'Uhuru Gardens, Nairobi',
        description: 'Experience the magic of Sauti Sol live under the stars. A night of unforgettable music and dance.',
        coverImageUrl: 'https://picsum.photos/seed/event1/600/400',
        createdBy: 'Ben Carter Events',
        category: 'Music',
        entryFee: 0,
        ticketType: 'single',
        distanceKm: 5.2,
    },
    {
        id: 2,
        name: 'Nairobi Tech Summit 2024',
        date: '2024-11-20T09:00:00',
        location: 'KICC, Nairobi',
        description: 'The premier tech conference in East Africa. Join industry leaders, innovators, and investors.',
        coverImageUrl: 'https://picsum.photos/seed/event2/600/400',
        createdBy: 'Tech Innovators KE',
        category: 'Conference',
        entryFee: 0,
        ticketType: 'multiple',
        distanceKm: 1.5,
    },
    {
        id: 3,
        name: 'Jane & John\'s Wedding',
        date: '2025-01-25T14:00:00',
        location: 'Windsor Golf Hotel & Country Club',
        description: 'Celebrating the union of Jane Doe and John Smith. A beautiful garden ceremony followed by a reception.',
        coverImageUrl: 'https://picsum.photos/seed/event3/600/400',
        createdBy: 'Festive Planners',
        category: 'Wedding',
        entryFee: 0,
        ticketType: 'single',
        distanceKm: 12.8,
    },
     {
        id: 4,
        name: 'Kilimani Community Cleanup',
        date: '2024-10-30T08:00:00',
        location: 'Kilimani Primary School',
        description: 'Join us in making our neighborhood cleaner and greener. Gloves and bags will be provided.',
        coverImageUrl: 'https://picsum.photos/seed/event4/600/400',
        createdBy: 'Amina Yusuf',
        category: 'Community',
        entryFee: 0,
        ticketType: 'multiple',
        distanceKm: 2.1,
    },
];

export const MOCK_USER_TICKETS: Ticket[] = [
    {
        id: 'TKT-1-9876',
        eventId: 1,
        eventName: 'Sauti Sol Live in Concert',
        eventDate: '2024-12-15T19:00:00',
        eventLocation: 'Uhuru Gardens, Nairobi',
        userName: 'Current User',
        qrCodeData: 'TKT-1-9876-USER123'
    }
];


export const MOCK_CATALOGUE_ITEMS: CatalogueItem[] = [
    {
        id: 1,
        providerId: 13, // Sarah Chen
        title: 'Bridal Makeup Package',
        category: 'Service',
        description: 'Complete bridal makeup including consultation, trial, and day-of application. A full-service package to make you look your best on your special day. Uses high-quality, long-lasting products.',
        price: 'Ksh 15,000',
        imageUrls: ['https://picsum.photos/seed/makeupcat1/400/300']
    },
    {
        id: 2,
        providerId: 13, // Sarah Chen
        title: 'Photoshoot Makeup',
        category: 'Service',
        description: 'Professional makeup for fashion, corporate, or personal photoshoots. Look includes skin prep, makeup application, and lashes.',
        price: 'Ksh 5,000',
        imageUrls: ['https://picsum.photos/seed/makeupcat2/400/300']
    },
    {
        id: 3,
        providerId: 6, // Ben Carter Events
        title: 'Corporate Event Catering',
        category: 'Service',
        description: 'Custom catering menus for corporate meetings, conferences, and parties. Price per head.',
        price: 'Starting at Ksh 2,500/person',
        imageUrls: ['https://picsum.photos/seed/webdev/400/300']
    },
    {
        id: 4,
        providerId: 6, // Ben Carter Events
        title: 'Luxury Tent for Hire',
        category: 'For Rent',
        description: 'High-peak marquee tent, 10x20 meters. Perfect for weddings and large gatherings.',
        price: 'Ksh 30,000/day',
        imageUrls: ['https://picsum.photos/seed/tent/400/300']
    }
];

export const MOCK_DOCUMENTS: Document[] = [
    {
        id: 'doc1',
        type: 'Invoice',
        number: 'INV-007',
        from: 'Roki Samuna',
        date: '2024-07-20',
        amount: 6500,
        currency: 'Ksh',
        status: 'Paid',
    },
    {
        id: 'doc2',
        type: 'Quote',
        number: 'QTE-012',
        from: 'Festive Planners',
        date: '2024-07-18',
        amount: 125000,
        currency: 'Ksh',
        status: 'Pending',
    },
    {
        id: 'doc3',
        type: 'Receipt',
        number: 'RCT-105',
        from: 'Jamila Ahusn',
        date: '2024-07-15',
        amount: 2500,
        currency: 'Ksh',
        status: 'Paid',
    },
    {
        id: 'doc4',
        type: 'Invoice',
        number: 'INV-006',
        from: 'Ben Carter Events',
        date: '2024-07-10',
        amount: 15000,
        currency: 'Ksh',
        status: 'Overdue',
    },
];

export const MOCK_INVITATIONS: Invitation[] = [
    {
        id: 'inv1',
        hostId: 1, // Roki Samuna
        hostName: 'Roki Samuna',
        visitorPhone: '0711223344',
        visitDate: new Date(Date.now() + 2 * 24 * 60 * 60 * 1000).toISOString().split('T')[0], // 2 days from now
        status: 'Active',
        accessCode: '123456',
    },
    {
        id: 'inv2',
        hostId: 2, // Jamila Ahusn
        hostName: 'Jamila Ahusn',
        visitorPhone: '0755667788',
        visitDate: new Date().toISOString().split('T')[0], // Today
        status: 'Active',
        accessCode: '654321',
    }
];

export const MOCK_SPECIAL_BANNERS: SpecialBanner[] = [
  {
    id: 1,
    imageUrl: 'https://picsum.photos/seed/promo1/600/400',
    targetCategory: 'Transport',
    targetLocation: 'Nairobi',
    minRating: 4.5
  },
  {
    id: 2,
    imageUrl: 'https://picsum.photos/seed/promo2/600/400',
    targetReferralCode: 'REDCROSS'
  }
];


export const DEFAULT_BANNERS: Record<string, string> = {
    'Home': 'https://picsum.photos/seed/homebanner/600/400',
    'Transport': 'https://picsum.photos/seed/transportbanner/600/400',
    'Emergency': 'https://picsum.photos/seed/emergencybanner/600/400',
    'Gas': 'https://picsum.photos/seed/gasbanner/600/400',
    'Event': 'https://picsum.photos/seed/eventbanner/600/400',
    'Personal': 'https://picsum.photos/seed/personalbanner/600/400',
    'Delivery': 'https://picsum.photos/seed/deliverybanner/600/400',
    'Travel': 'https://picsum.photos/seed/travelbanner/600/400',
};

export const REFERRAL_CODES: Record<string, { isVerified: boolean; banner: string; category: string }> = {
    'REDCROSS': { isVerified: true, banner: 'https://picsum.photos/seed/redcrossbanner/600/400', category: 'Emergency' },
    'STJOHN': { isVerified: true, banner: 'https://picsum.photos/seed/stjohnbanner/600/400', category: 'Emergency' },
};

export const MOCK_INBOX_MESSAGES: InboxMessage[] = [
  {
    id: 1,
    from: 'Soko Team',
    subject: 'Welcome to Niko Soko!',
    body: 'Hi there! Welcome to the community. We are excited to have you on board. Explore services, connect with providers, and grow your own business with our toolkit. If you have any questions, feel free to reach out to our support team.',
    timestamp: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
    isRead: false,
  },
  {
    id: 2,
    from: 'Soko Team',
    subject: 'New Feature: Gate Pass System',
    body: 'We have just launched our new Gate Pass system for hosts to easily manage their visitors. Check it out in the Tool Box on the main page!',
    timestamp: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
    isRead: true,
  },
  {
    id: 3,
    from: 'Soko Team',
    subject: 'Profile Verification Update',
    body: 'To improve trust and safety on our platform, we have updated our profile verification process. Verified users now have a blue checkmark on their profile. Consider completing your profile to get verified today.',
    timestamp: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000).toISOString(),
    isRead: true,
  },
];